### ISSUE TITLE
Vicuna Result Reproduction

### ISSUE THREAD

**Issue by chenhongqiao** [Yifan-Song793/RestGPT#5]
Greetings!

I'm wondering if you could release the local inference service code used to connect Vicuna and LLaMA to LangChain? That'll help a lot in reproducing the paper's result and aid further research. Thanks!

**Comment by Yifan-Song793** [comment]
Since RestGPT is built upon LangChain, it is easy to change the base LLM to Vicuna. 

Take `run_tmdb.py` for example, you can replace line 17:
```python
llm = OpenAI(model_name="text-davinci-003", temperature=0.0, max_tokens=256)
```
with
```python
model = "lmsys/vicuna-13b-v1.5"
tokenizer = AutoTokenizer.from_pretrained(model)
pipe = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer, 
    max_new_tokens=256,
    device_map="auto",
    pad_token_id=tokenizer.eos_token_id,
)
llm = HuggingFacePipeline(pipeline=pipe)
```
to use Vicuna as the base LLM.

In our paper, we use the same prompt for all LLMs for a fair comparison. However, Vicuna and Llama are sensitive to the prompt, and the prompt for GPT may not be optimal for Vicuna. Therefore, if you use this repo for your research, further prompt engineering may be needed.
